name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ayushmanpathak9034
          outputs: |
            github-contribution-grid-snake.svg

      - name: Commit Snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate snake animation"
